site_name: Quantalyze
nav:
  - Home: index.md
  - Core:
      - Overview: core.md
      - Fitting: fitting.md
      - Differentiation: differentiation.md
      - Smoothing: smoothing.md
      - Symmetrization: symmetrization.md
  - Transport: transport.md
  - Plotting: plotting.md
  - Thermometry: thermometry.md
theme:
  name: material
plugins:
  - search
  - mkdocstrings